# Development React client
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY client/package*.json ./

# Get version from package.json and set as build arg
ARG VERSION
ENV REACT_APP_VERSION=$VERSION

# Install dependencies
RUN npm install

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "start"] 