version: '3.8'

services:
  # MariaDB Database
  db:
    image: mariadb:10.6
    container_name: church_attendance_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mariadb", "-u", "${DB_USER}", "-p${DB_PASSWORD}", "-e", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js Backend Server
  server:
    image: staugustine1/letmypeoplegrow-server:${IMAGE_TAG}
    container_name: church_attendance_server
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${SERVER_PORT}
      CLIENT_URL: ${CLIENT_URL}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      OTC_EXPIRE_MINUTES: ${OTC_EXPIRE_MINUTES}
      OTC_RESEND_COOLDOWN_SECONDS: ${OTC_RESEND_COOLDOWN_SECONDS}
      EMAIL_FROM: ${EMAIL_FROM}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM_NUMBER: ${TWILIO_FROM_NUMBER}
      BREVO_API_KEY: ${BREVO_API_KEY}
    ports:
      - "${SERVER_PORT}:3001"
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # React Frontend Client
  client:
    image: staugustine1/letmypeoplegrow-client:${IMAGE_TAG}
    container_name: church_attendance_client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT}:3000"
    depends_on:
      - server
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: church_attendance_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl:ro  # Optional: for SSL certificates
    depends_on:
      - client
      - server
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge 